services:

  traefik:
    image: traefik:3.1
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=gnebehay@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  schosel-backend:
    restart: unless-stopped
    volumes:
      - /home/georg/data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.schosel-backend.rule: "(Host(\"schosel.net\") || Host(\"www.schosel.net\")) && PathPrefix(`/api`)"
      traefik.http.routers.schosel-backend.entrypoints: websecure
      traefik.http.routers.schosel-backend.tls: "true"
      traefik.http.routers.schosel-backend.tls.certresolver: myresolver
      traefik.http.services.schosel-backend.loadbalancer.server.port: "8000"
    environment:
      SQLALCHEMY_DATABASE_URI: "sqlite:////app/data/app.db"
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
    build: .

  schosel-frontend:
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.schosel-frontend.rule: "Host(\"schosel.net\") || Host(\"www.schosel.net\")"
      traefik.http.routers.schosel-frontend.tls: "true"
      traefik.http.routers.schosel-frontend.tls.certresolver: myresolver
      traefik.http.services.schosel-frontend.loadbalancer.server.port: "80"
    build: ../schosel-frontend