"""Add avatar salt

Revision ID: 27613b54bcac
Revises: 437f82551640
Create Date: 2021-04-19 21:28:17.807217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27613b54bcac'
down_revision = '437f82551640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_salt', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_salt')
    # ### end Alembic commands ###
