"""initial

Revision ID: 30bdc7118921
Revises: 
Create Date: 2026-05-09 23:32:10.425083

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '30bdc7118921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=3), nullable=False),
    sa.Column('group', sa.String(length=1), nullable=False),
    sa.Column('champion', sa.Boolean(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(length=256), nullable=False),
    sa.Column('goals_team1', sa.Integer(), nullable=True),
    sa.Column('goals_team2', sa.Integer(), nullable=True),
    sa.Column('first_goal', sa.Enum('1', 'X', '2', name='outcome'), nullable=False),
    sa.Column('over', sa.Boolean(), nullable=False),
    sa.Column('odds_team1', sa.Float(), nullable=False),
    sa.Column('odds_draw', sa.Float(), nullable=False),
    sa.Column('odds_team2', sa.Float(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team1_id', 'team2_id', 'stage')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('avatar_salt', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('schosel_points', sa.Float(), nullable=False),
    sa.Column('loser_points', sa.Float(), nullable=False),
    sa.Column('underdog_points', sa.Float(), nullable=False),
    sa.Column('balanced_points', sa.Float(), nullable=False),
    sa.Column('comeback_points', sa.Float(), nullable=False),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('1', 'X', '2', name='outcome'), nullable=True),
    sa.Column('supertip', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
